Repository devopness/devopness, pull requests merged in 2022-06, with the labels that each got.

#523 docs: Add `Building and testing` section to README
  README.md
Labels: cla-signed

#524 refactor: Update service code to enum
  src/api/generated/models/cloud-service.ts
  src/api/generated/models/server-cloud-service-name.ts
  src/api/spec.json
Labels: cla-signed

#525 feat: update incoming and outgoing hook models
  src/api/generated/apis/hooks-incoming-api.ts
  src/api/generated/apis/hooks-outgoing-api.ts
  src/api/generated/apis/hooks-requests-api.ts
  src/api/generated/models/hook-incoming-create.ts
  src/api/generated/models/hook-incoming-params.ts
  src/api/generated/models/hook-incoming-setting.ts
  src/api/generated/models/hook-incoming-update.ts
  src/api/generated/models/hook-incoming.ts
  src/api/generated/models/hook-outgoing-create.ts
  src/api/generated/models/hook-outgoing-params.ts
  src/api/generated/models/hook-outgoing-request-header.ts
  src/api/generated/models/hook-outgoing-setting.ts
  src/api/generated/models/hook-outgoing-update.ts
  src/api/generated/models/hook-outgoing.ts
  src/api/generated/models/hook-relation.ts
  src/api/generated/models/hook.ts
  src/api/generated/models/index.ts
  src/api/spec.json
Labels: cla-signed

#526 feat: Expose `url_web_permalink` on `GET /actions/{id}`
  src/api/generated/models/action.ts
  src/api/spec.json
Labels: cla-signed

#529 refactor: Output auto-generated docs to SDK specific folder
  .gitignore
  typedoc.json
Labels: cla-signed

#528 fix: Rename cloud services to contain cloud provider prefix
  src/api/generated/models/cloud-service.ts
  src/api/generated/models/server-cloud-service-name.ts
  src/api/spec.json
Labels: cla-signed

#531 ci: Add linter to validate PR attributes
  .github/workflows/lint-pr-title.yml
Labels: cla-signed

#533 ci: Set main branch and default dir in workflows
  .github/workflows/sdk-javascript-ci.yml
  .github/workflows/sdk-javascript-release.yml
Labels: cla-signed

#535 docs: Add README and move husky
  README.md
  docs/README.md
  packages/sdks/javascript/.husky/.gitignore
  packages/sdks/javascript/.husky/pre-push
  packages/sdks/javascript/README.md
Labels: cla-signed

#536 ci: Add labels based on PRs changed files
  .github/labeler-pr.yml
  .github/workflows/label-pr.yml
  .github/workflows/sdk-javascript-ci.yml
Labels: cla-signed

#538 chore: Add comment on safe usage of pull_request_target
  .github/workflows/label-pr.yml
  .github/workflows/lint-pr-title.yml
Labels: cla-signed, ci

#540 fix: Rename release branch to use `main`
  packages/sdks/javascript/package.json
Labels: cla-signed, packages, sdk, sdk-javascript
